flags:
  wxc:
    package: true
  reactive-banana-wx:
    buildExamples: true
packages:
- '.'
extra-deps:
- fgl-5.4.2.4
- cabal-macosx-0.2.3
- pqueue-1.3.1
- reactive-banana-0.9.0.0
- reactive-banana-wx-0.9.0.2
- wx-0.92.0.0
- wxc-0.92.1.1
- wxcore-0.92.1.0
- wxdirect-0.92.1.0
- random-1.0.1.0
- split-0.2.2
resolver: lts-2.22
